language: python
python:
  - "3.8"
  - "3.9"

install:
  # Install Anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -c conda-forge --file requirements.txt
  - python setup.py install

script:
  - pytest

after_success:
  - conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh