package:
  name: lorat
  version: {{ environ['VERSION'] }}

source:
  path: ../

build:
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - reportlab
    - pypdf2
    - psutil

  run:
    - python
    - setuptools
    - numpy
    - matplotlib
    - reportlab
    - pypdf2
    - psutil

  entry_points:
    - lorat-simulation = lorat.__init__:lorat-simulation
    - lorat-explorer = lorat.__init__:lorat-explorer

about:
  summary: This is a simple meta-package

extra:
  recipe-maintainers:
    -dragosbogatu
    -mateisarivan