package:
  name: lorat
  version: 0.0.6

source:
  path: ../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - matplotlib
    - reportlab
    - pypdf2
    - psutil

  entry_points:
    - lorat-simulation = lorat.__init__:lorat-simulation
    - lorat-explorer = lorat.__init__:lorat-explorer

about:
  summary: This is a simple meta-package

extra:
  recipe-maintainers:
    -dragosbogatu
    -mateisarivan