package:
  name: lorat
  version: 0.0.1

source:
  path: ../

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

  entry_points:
    - lorat = lorat.__init__:main

about:
  summary: This is a simple meta-package

extra:
  recipe-maintainers:
    -dragosbogatu
    -mateisarivan